name: Deploy Mule API

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - stg

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Deploy
        run: |
          mvn clean deploy \
          -DmuleDeploy \
          -DskipTests \
          -Dapp.name=bank-account-eapi \
          -Denvironment=Sandbox \
          -Danypoint.username=${{ secrets.ANYPOINT_USERNAME }} \
          -Danypoint.password=${{ secrets.ANYPOINT_PASSWORD }}
